### ISSUE TITLE
Request_to_chat

### ISSUE THREAD

**Issue by CodeGeek04** [Pratiyush27/Blockchain_for_user_authentication#1]
Hey there Pratiyush, Shivam here. First of all I am pretty new to Github, so I didnt knew how to talk to someone via there profile. So I decided to initiate an issue so that we can have a conversation, please tell me another platform that might suit you. I am available on telegram and discord if you prefer privacy.I just wanted to have a conversation regarding our team in the Microsoft Hackathon...Cya later

**Comment by Codes5761** [comment]
Hey Shivam, you can mail me the team conversation platform with chatroom link on prakashpratiyush@gmail.com

**Comment by Pratiyush27** [comment]
Hey Shivam, you can mail me the team conversation platform with chatroom link on prakashpratiyush@gmail.com
